//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActAccountMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActAccountMaster()
        {
            this.ActAccountCenterwises = new HashSet<ActAccountCenterwise>();
            this.GeneralTypeOfAccountMapWithAccounts = new HashSet<GeneralTypeOfAccountMapWithAccount>();
        }
    
        public short ID { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public Nullable<short> GroupID { get; set; }
        public string DebitCreditFlag { get; set; }
        public string CashBankFlag { get; set; }
        public string BackDatetimedEntries { get; set; }
        public Nullable<short> PrintingSequence { get; set; }
        public string PersonType { get; set; }
        public string OpBalRequired { get; set; }
        public Nullable<bool> ExclusivelyForCentre { get; set; }
        public string IgnoreChequeNo { get; set; }
        public Nullable<short> AltGroupID { get; set; }
        public Nullable<bool> TrialBalSubledger { get; set; }
        public string SurpDifiFlag { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActAccountCenterwise> ActAccountCenterwises { get; set; }
        public virtual ActGroupMaster ActGroupMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralTypeOfAccountMapWithAccount> GeneralTypeOfAccountMapWithAccounts { get; set; }
    }
}
