//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActBankTransaction
    {
        public long ID { get; set; }
        public Nullable<short> AccountID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public string DebitCreditFlag { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDatetime { get; set; }
        public Nullable<int> ReconciliationID { get; set; }
        public Nullable<System.DateTime> ReconciliationDate { get; set; }
        public string NarrationDescription { get; set; }
        public Nullable<short> AccBalsheetMstID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
