//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActBankDetail
    {
        public short ID { get; set; }
        public Nullable<short> AccountID { get; set; }
        public string BankAccountNumber { get; set; }
        public string AccountInNameOf { get; set; }
        public string BankBranchName { get; set; }
        public Nullable<decimal> BankLimitAmount { get; set; }
        public Nullable<decimal> RateOfInterest { get; set; }
        public string InterestMode { get; set; }
        public string InterestType { get; set; }
        public Nullable<System.DateTime> OpenDatetime { get; set; }
        public Nullable<System.DateTime> DueDatetime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
