//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActCentreOpeningBalance
    {
        public int ID { get; set; }
        public Nullable<short> ActSessionID { get; set; }
        public Nullable<short> AccountID { get; set; }
        public Nullable<System.DateTime> OpeningDatetime { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> TotalDebitAmount { get; set; }
        public Nullable<decimal> TotalCreditAmount { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<short> ActBalsheetMstID { get; set; }
        public bool IsCarryForward { get; set; }
    }
}
