//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActChequeBookMaster
    {
        public int ID { get; set; }
        public Nullable<short> AccountID { get; set; }
        public Nullable<int> ChequeFromNo { get; set; }
        public Nullable<int> ChequeToNo { get; set; }
        public Nullable<short> TotalNoCheque { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
        public Nullable<short> ActBalsheetMstID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CentreCode { get; set; }
    }
}
