//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActChequeBookDetail
    {
        public long ID { get; set; }
        public Nullable<int> ChequeBookID { get; set; }
        public Nullable<int> ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDatetime { get; set; }
        public Nullable<decimal> ChequeAmount { get; set; }
        public Nullable<long> TransactionMainID { get; set; }
        public Nullable<long> TransactionSubID { get; set; }
        public Nullable<System.DateTime> TransactionDatetime { get; set; }
        public string ChequeStatus { get; set; }
        public string ChequeDescription { get; set; }
        public string CentreCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
