//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActSessionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActSessionMaster()
        {
            this.GeneralRunningNumbersForAccounts = new HashSet<GeneralRunningNumbersForAccount>();
        }
    
        public short ID { get; set; }
        public Nullable<System.DateTime> SessionStartDatetime { get; set; }
        public Nullable<System.DateTime> SessionEndDatetime { get; set; }
        public Nullable<bool> DefaultFlag { get; set; }
        public string Account_System { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<short> OldSessionID { get; set; }
        public Nullable<bool> IsSessionClosed { get; set; }
        public Nullable<bool> IsBalanceCarryForward { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralRunningNumbersForAccount> GeneralRunningNumbersForAccounts { get; set; }
    }
}
