//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActTransactionDetail
    {
        public long ID { get; set; }
        public Nullable<long> TransactionMainID { get; set; }
        public Nullable<short> AccountID { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public string DebitCreditFlag { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDatetime { get; set; }
        public string NarrationDescription { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public Nullable<System.DateTime> BankClearingDatetime { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string ModeCode { get; set; }
        public string PersonType { get; set; }
        public Nullable<short> ActSessionID { get; set; }
        public Nullable<long> VoucherNumber { get; set; }
        public string SubmitSlipNo { get; set; }
        public Nullable<System.DateTime> SubmitDatetime { get; set; }
        public Nullable<System.DateTime> ReconcilationDatetime { get; set; }
        public Nullable<short> ActBalsheetMstID { get; set; }
        public string BankTransferFlag { get; set; }
        public string ChqDepositSlipNo { get; set; }
        public Nullable<System.DateTime> ChqDepositDatetime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ReferencePersonType { get; set; }
        public Nullable<int> ReferencePersonID { get; set; }
    }
}
