//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminSanctionPost : RARIndiaEntityBaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminSanctionPost()
        {
            this.AdminRoleMasters = new HashSet<AdminRoleMaster>();
        }
    
        public int AdminSanctionPostId { get; set; }
        public short DesignationId { get; set; }
        public short NoOfPost { get; set; }
        public short DepartmentId { get; set; }
        public bool IsActive { get; set; }
        public string CentreCode { get; set; }
        public string DesignationType { get; set; }
        public string SanctionPostCode { get; set; }
        public string PostType { get; set; }
        public string SanctionedPostDescription { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminRoleMaster> AdminRoleMasters { get; set; }
        public virtual GeneralDepartmentMaster GeneralDepartmentMaster { get; set; }
        public virtual EmployeeDesignationMaster EmployeeDesignationMaster { get; set; }
    }
}
