//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using RARIndia.Model;

    using System;
    using System.Collections.Generic;
    
    public partial class AdminRoleMaster: RARIndiaEntityBaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminRoleMaster()
        {
            this.AdminRoleApplicableDetails = new HashSet<AdminRoleApplicableDetail>();
            this.AdminRoleMenuDetails = new HashSet<AdminRoleMenuDetail>();
        }
    
        public short ID { get; set; }
        public short AdminSnPostID { get; set; }
        public string SanctPostName { get; set; }
        public string MonitoringLevel { get; set; }
        public string AdminRoleCode { get; set; }
        public string OthCentreLevel { get; set; }
        public Nullable<bool> IsLoginAllowFromOutside { get; set; }
        public Nullable<bool> IsAttendaceAllowFromOutside { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminRoleApplicableDetail> AdminRoleApplicableDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminRoleMenuDetail> AdminRoleMenuDetails { get; set; }
    }
}
