//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminRoleSpecialRightDetail
    {
        public short ID { get; set; }
        public Nullable<short> AdminRoleSpecialRightMasterID { get; set; }
        public Nullable<short> AdminRoleRightTypeID { get; set; }
        public string CentreCode { get; set; }
        public Nullable<System.DateTime> EnableDate { get; set; }
        public Nullable<System.DateTime> DisableDate { get; set; }
        public string DisablePurpose { get; set; }
        public Nullable<short> AdminRoleEntityID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
