//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerMaster()
        {
            this.CustomerBranchMasters = new HashSet<CustomerBranchMaster>();
            this.CustomerContactDetails = new HashSet<CustomerContactDetail>();
            this.SalesEnquiryMasters = new HashSet<SalesEnquiryMaster>();
            this.SalesOrderMasters = new HashSet<SalesOrderMaster>();
            this.SalesQuotationMasters = new HashSet<SalesQuotationMaster>();
        }
    
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<byte> CustomerType { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<short> StateID { get; set; }
        public Nullable<short> CountryID { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<short> Currency { get; set; }
        public Nullable<byte> CreditPeriod { get; set; }
        public Nullable<byte> UnitMasterID { get; set; }
        public string GSTNumber { get; set; }
        public Nullable<bool> IsTaxExempted { get; set; }
        public Nullable<byte> ReasonForExemption { get; set; }
        public string BankName { get; set; }
        public string IFCICODE { get; set; }
        public string BankAccountNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<short> CustomerSectorTypeId { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<int> NoOfBranches { get; set; }
        public string PinCode { get; set; }
        public string TaxExemptionRemark { get; set; }
        public Nullable<bool> IsCentre { get; set; }
        public string CentreCode { get; set; }
        public string PanNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBranchMaster> CustomerBranchMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContactDetail> CustomerContactDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesEnquiryMaster> SalesEnquiryMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderMaster> SalesOrderMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesQuotationMaster> SalesQuotationMasters { get; set; }
    }
}
