//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBranchMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerBranchMaster()
        {
            this.CustomerContactDetails = new HashSet<CustomerContactDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerMasterID { get; set; }
        public Nullable<bool> IsMainBranch { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<short> StateID { get; set; }
        public Nullable<short> CountryID { get; set; }
        public string GSTNumber { get; set; }
        public Nullable<bool> IsTaxExempted { get; set; }
        public Nullable<byte> ReasonForExemption { get; set; }
        public Nullable<byte> CreditPeriod { get; set; }
        public Nullable<byte> UnitMasterID { get; set; }
        public string BankName { get; set; }
        public string IFCICODE { get; set; }
        public string BankAccountNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string BranchName { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public string ShortCode { get; set; }
        public Nullable<bool> IsBillToSameAsShipTo { get; set; }
        public string CustomerBranchCode { get; set; }
        public string PinCode { get; set; }
        public string TaxExemptionRemark { get; set; }
        public Nullable<bool> IsCentre { get; set; }
        public string CentreCode { get; set; }
        public bool IsCustomSalaryStructure { get; set; }
        public string PanNumber { get; set; }
    
        public virtual CustomerMaster CustomerMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContactDetail> CustomerContactDetails { get; set; }
    }
}
