//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeExperience
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> ExperienceFromYear { get; set; }
        public Nullable<System.DateTime> ExperienceToYear { get; set; }
        public Nullable<short> ExperienceInMonth { get; set; }
        public string PreviousOrganisationName { get; set; }
        public string PreviousOrgnisationAddress { get; set; }
        public string Designation { get; set; }
        public string Remarks { get; set; }
        public int GeneralExperienceTypeMasterID { get; set; }
        public string LastPayDrawnPayScale { get; set; }
        public string NatureOfAppointment { get; set; }
        public Nullable<int> GeneralJobStatusID { get; set; }
        public string AppointmentOrderNumber { get; set; }
        public Nullable<System.DateTime> AppointmentOrderDate { get; set; }
        public string UniversityApprovalNumber { get; set; }
        public Nullable<System.DateTime> UniversityApprovalDate { get; set; }
        public int GeneralBoardUniversityID { get; set; }
        public string SubjectForApproval { get; set; }
        public string UniversityApprovalType { get; set; }
        public Nullable<short> MonthOfApproval { get; set; }
        public Nullable<short> YearOfApproval { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
