//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeServiceDetail
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string AcceptedByEmployee { get; set; }
        public string PromotionDemotionFlag { get; set; }
        public Nullable<System.DateTime> PromotionDemotionDate { get; set; }
        public Nullable<System.DateTime> PreviousPromotionDemotionDate { get; set; }
        public Nullable<int> EmployeeDesignationMasterID { get; set; }
        public string CentreCode { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<System.DateTime> ChargeTakingDate { get; set; }
        public Nullable<int> OldDesignationID { get; set; }
        public string OldCentreCode { get; set; }
        public Nullable<int> OldDepartmentID { get; set; }
        public Nullable<System.DateTime> CollegeApprovalDate { get; set; }
        public Nullable<System.DateTime> UniversityApprovalDate { get; set; }
        public string CollegeApprovalNumber { get; set; }
        public string UniversityApprovalNumber { get; set; }
        public string NatureOfDuty { get; set; }
        public Nullable<decimal> BasicAmount { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<decimal> NewGrade { get; set; }
        public Nullable<int> NewPayscaleID { get; set; }
        public string NatureOfAppointment { get; set; }
        public string UniversityApprovalType { get; set; }
        public Nullable<int> GeneralBoardUniversityID { get; set; }
        public string SubjectForApproval { get; set; }
        public Nullable<System.DateTime> GrantedPromotionDate { get; set; }
        public Nullable<int> GrantedPromotionDesignationID { get; set; }
        public string GrantedPromotionLevel { get; set; }
        public bool IsCurrentFlag { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
