//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeQualification
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public string FromYear { get; set; }
        public string UptoYear { get; set; }
        public string YearOfPassing { get; set; }
        public string PassingDivision { get; set; }
        public Nullable<byte> NoOfAttempts { get; set; }
        public string NameOfInstitution { get; set; }
        public Nullable<int> EducationTypeID { get; set; }
        public Nullable<int> EducationID { get; set; }
        public string EducationYear { get; set; }
        public string Unit { get; set; }
        public Nullable<int> BoardUniversityID { get; set; }
        public Nullable<double> AggregatePercentage { get; set; }
        public Nullable<double> FinalYearPercentage { get; set; }
        public Nullable<byte> Rank { get; set; }
        public string Remark { get; set; }
        public string SpecailisationIn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
