//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public int ID { get; set; }
        public string EmployeeCode { get; set; }
        public string EmailID { get; set; }
        public string OtherEmailID { get; set; }
        public string NameTitle { get; set; }
        public string MrOrMrs { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeMiddleName { get; set; }
        public string EmployeeLastName { get; set; }
        public string NickName { get; set; }
        public Nullable<bool> IsEmployeeSmoker { get; set; }
        public string EthanicRaceCode { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public string GenderCode { get; set; }
        public string MarritalStaus { get; set; }
        public string SSNNumber { get; set; }
        public string SINNumber { get; set; }
        public string DrivingLicenceNumber { get; set; }
        public Nullable<System.DateTime> DrivingLicenceExpireDate { get; set; }
        public string TelephoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string PanNumber { get; set; }
        public string ESINumber { get; set; }
        public string ProvidentFundNumber { get; set; }
        public Nullable<System.DateTime> ProvidentFundApplicableDate { get; set; }
        public string BankACNumber { get; set; }
        public Nullable<int> EmployeeShiftApplicableMasterID { get; set; }
        public string SalaryGradeCode { get; set; }
        public Nullable<System.DateTime> AppointmentApprovalDate { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<bool> IsLeave { get; set; }
        public Nullable<System.DateTime> DateOfLeaving { get; set; }
        public Nullable<System.DateTime> DateOfRetirment { get; set; }
        public Nullable<int> TerminationID { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> CentrewiseDeptID { get; set; }
        public int EmployeeDesignationMasterID { get; set; }
        public Nullable<int> JobStatusID { get; set; }
        public string JobStatus { get; set; }
        public Nullable<int> JobProfileID { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public string UserRemark { get; set; }
        public string ReasonOfLeaving { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<int> PayScaleMstID { get; set; }
        public string PaymentMode { get; set; }
        public string CentreCode { get; set; }
        public string EmployeeNameAsPerTC { get; set; }
        public string MaidenFirstName { get; set; }
        public string MaidenMiddleName { get; set; }
        public string MaidenLastName { get; set; }
        public Nullable<bool> IsNameChangedBefore { get; set; }
        public string PriorFirstName { get; set; }
        public string PriorMiddleName { get; set; }
        public string PriorLastName { get; set; }
        public Nullable<int> BioMatrixEmployeeID { get; set; }
        public string AdharCardNumber { get; set; }
        public Nullable<int> EnquiryLevelID { get; set; }
        public Nullable<int> ActiveCommissionID { get; set; }
        public string custom1 { get; set; }
        public string custom2 { get; set; }
        public string custom3 { get; set; }
        public string custom4 { get; set; }
        public string custom5 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string InActiveReason { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string UANNumber { get; set; }
    }
}
