//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralRequestMaster
    {
        public int ID { get; set; }
        public string RequestCode { get; set; }
        public string RequestDescription { get; set; }
        public string MenuCode { get; set; }
        public string LinkMenuCode { get; set; }
        public string RequestApprovalBasedTable { get; set; }
        public string RequestApprovalParamPrimaryKey { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    }
}
