//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralSupplierMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralSupplierMaster()
        {
            this.PurchaseRequisitionMasters = new HashSet<PurchaseRequisitionMaster>();
            this.PurchaseReturnMasters = new HashSet<PurchaseReturnMaster>();
            this.VendorContactPersonInfoes = new HashSet<VendorContactPersonInfo>();
            this.VendorFinanceDetails = new HashSet<VendorFinanceDetail>();
            this.VendorReplenishmentInfoes = new HashSet<VendorReplenishmentInfo>();
        }
    
        public int ID { get; set; }
        public string Vender { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public string AddressFirst { get; set; }
        public string AddressSecond { get; set; }
        public string PlotNumber { get; set; }
        public string StreetNumber { get; set; }
        public Nullable<int> TahsilID { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string PhoneNumber { get; set; }
        public string ResiPhoneNumber { get; set; }
        public string CellPhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Email { get; set; }
        public string WebUrl { get; set; }
        public string VenderDescription { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string VAT { get; set; }
        public string CST { get; set; }
        public string Excise { get; set; }
        public string StablishmentNumber { get; set; }
        public string RefNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> VendorNumber { get; set; }
        public Nullable<short> Country { get; set; }
        public string Currency { get; set; }
        public string AddressThird { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<decimal> VendorRestriction { get; set; }
        public Nullable<bool> ReturnGoods { get; set; }
        public Nullable<bool> IsOtherState { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public string VendorCode { get; set; }
        public Nullable<bool> IsCentre { get; set; }
        public string CentreCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRequisitionMaster> PurchaseRequisitionMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseReturnMaster> PurchaseReturnMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorContactPersonInfo> VendorContactPersonInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorFinanceDetail> VendorFinanceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorReplenishmentInfo> VendorReplenishmentInfoes { get; set; }
    }
}
