//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralItemCategoryMaster
    {
        public short ID { get; set; }
        public string ItemCategoryDescription { get; set; }
        public string ItemCategoryCode { get; set; }
        public short MarchandiseGroupID { get; set; }
        public short MerchantiseDepartmentID { get; set; }
        public short MerchantiseCategoryID { get; set; }
        public short MarchandiseSubCategoryID { get; set; }
        public short MarchandiseBaseCatgoryId { get; set; }
        public Nullable<int> SalesAccount { get; set; }
        public Nullable<int> InventoryAccount { get; set; }
        public Nullable<int> COGSAccount { get; set; }
        public Nullable<int> InventoryAdjustmentAccount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsConsumable { get; set; }
        public Nullable<bool> IsMachine { get; set; }
        public Nullable<bool> IsToner { get; set; }
    }
}
