//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralTaskReportingMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralTaskReportingMaster()
        {
            this.GeneralTaskReportingDetails = new HashSet<GeneralTaskReportingDetail>();
            this.TaskNotificationMasters = new HashSet<TaskNotificationMaster>();
        }
    
        public int ID { get; set; }
        public string TaskCode { get; set; }
        public int NumberOfApprovalStages { get; set; }
        public string CentreCode { get; set; }
        public string TaskApprovalBasedTable { get; set; }
        public string TaskApprovalParamPrimaryKey { get; set; }
        public Nullable<int> TaskApprovalKeyValue { get; set; }
        public string TaskApprovalDisplayKey { get; set; }
        public string TaskApprovalDisplayKeyValue { get; set; }
        public string ApprovalType { get; set; }
        public string IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralTaskReportingDetail> GeneralTaskReportingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskNotificationMaster> TaskNotificationMasters { get; set; }
    }
}
