//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralRegionMaster : RARIndiaEntityBaseModel
    {
        public short GeneralRegionMasterId { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> DefaultFlag { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsUserDefined { get; set; }
        public Nullable<short> TinNumber { get; set; }
    }
}
