//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralItemCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralItemCode()
        {
            this.PurchaseInvoiceDetails = new HashSet<PurchaseInvoiceDetail>();
            this.PurchaseReturnTransactions = new HashSet<PurchaseReturnTransaction>();
        }
    
        public int ID { get; set; }
        public int GeneralItemMasterID { get; set; }
        public int ItemNumber { get; set; }
        public string BarCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsBaseUom { get; set; }
        public string UomCode { get; set; }
        public string LowerLevelUomCode { get; set; }
        public Nullable<double> ConversionFactor { get; set; }
        public Nullable<bool> IsOrderingUnit { get; set; }
        public Nullable<bool> IsSaleUnit { get; set; }
        public Nullable<bool> IsIssueUnit { get; set; }
        public string NewUomName { get; set; }
        public Nullable<double> BaseQuantity { get; set; }
        public string BaseUomCode { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseReturnTransaction> PurchaseReturnTransactions { get; set; }
    }
}
