//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralCountryMaster
    {
        public short ID { get; set; }
        public string CountryName { get; set; }
        public string ContryCode { get; set; }
        public Nullable<bool> IsUserDefined { get; set; }
        public Nullable<bool> DefaultFlag { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public string CurrencyCode { get; set; }
        public string currencySymbol { get; set; }
        public byte[] CountryFlag { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
