//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralUnit
    {
        public short ID { get; set; }
        public string UnitName { get; set; }
        public Nullable<short> GeneralUnitTypeID { get; set; }
        public string CentreCode { get; set; }
        public Nullable<short> DepartmentID { get; set; }
        public string LocationAddress { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Footer { get; set; }
        public string LogoPath { get; set; }
        public string Pincode { get; set; }
        public string TelephoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmailID { get; set; }
        public string Url { get; set; }
        public string DisplayIcon { get; set; }
        public string Greeting { get; set; }
        public Nullable<bool> IsFooter { get; set; }
        public Nullable<bool> IsLogoPath { get; set; }
        public Nullable<bool> IsPincode { get; set; }
        public Nullable<bool> IsTelephoneNumber { get; set; }
        public Nullable<bool> IsFaxNumber { get; set; }
        public Nullable<bool> IsEmailID { get; set; }
        public Nullable<bool> IsUrl { get; set; }
        public Nullable<bool> isGreeting { get; set; }
        public Nullable<bool> IsAddress { get; set; }
        public Nullable<bool> IsCityName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsDefaultUnit { get; set; }
    
        public virtual GeneralUnitType GeneralUnitType { get; set; }
    }
}
