//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralItemMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralItemMaster()
        {
            this.InventoryItemStoreSpecificInfoes = new HashSet<InventoryItemStoreSpecificInfo>();
        }
    
        public int ID { get; set; }
        public int ItemNumber { get; set; }
        public string ItemDescription { get; set; }
        public string ItemCategoryCode { get; set; }
        public Nullable<double> LastPurchasePrice { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<int> InventoryPurchaseGroupMasterId { get; set; }
        public Nullable<bool> IsInventoryItem { get; set; }
        public Nullable<bool> IsSalesItem { get; set; }
        public Nullable<bool> IsPurchaseItem { get; set; }
        public Nullable<bool> IsFixedAssetItem { get; set; }
        public Nullable<bool> IsRestaurant { get; set; }
        public Nullable<bool> IsMultipleVendor { get; set; }
        public Nullable<bool> IsEComItem { get; set; }
        public Nullable<bool> ISBOM { get; set; }
        public string UoMGroupCode { get; set; }
        public byte ItemType { get; set; }
        public Nullable<short> GenTaxGroupMasterId { get; set; }
        public Nullable<bool> RetailSale { get; set; }
        public string EComDisplayName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string HSNCode { get; set; }
        public Nullable<bool> IsServiceItem { get; set; }
        public string ItemCode { get; set; }
        public Nullable<bool> IsConsumable { get; set; }
        public Nullable<bool> IsMachine { get; set; }
        public Nullable<bool> IsToner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemStoreSpecificInfo> InventoryItemStoreSpecificInfoes { get; set; }
    }
}
