//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralRequestTransaction
    {
        public int ID { get; set; }
        public string RequestCode { get; set; }
        public int FromPersonID { get; set; }
        public string FromPersonType { get; set; }
        public int ToPersonID { get; set; }
        public string ToPersonType { get; set; }
        public int PrimaryKeyValue { get; set; }
        public byte Status { get; set; }
        public string Remark { get; set; }
        public byte IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    }
}
