//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralTypeOfAccountMapWithAccount
    {
        public short ID { get; set; }
        public Nullable<short> GeneralTypeOfAccountId { get; set; }
        public string AccountCode { get; set; }
        public Nullable<short> AccountMasterId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ActAccountMaster ActAccountMaster { get; set; }
        public virtual GeneralTypeOfAccount GeneralTypeOfAccount { get; set; }
    }
}
