//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralItemSupliersData
    {
        public int ID { get; set; }
        public int ItemNumber { get; set; }
        public int GeneralVendorID { get; set; }
        public string ManufacturCatalogNumber { get; set; }
        public string PurchaseUoMCode { get; set; }
        public Nullable<byte> GeneralPurchaseGroupMasterID { get; set; }
        public Nullable<short> GenTaxGroupMasterID { get; set; }
        public string PackageType { get; set; }
        public string CentreCode { get; set; }
        public Nullable<double> LastPurchasePrice { get; set; }
        public string PuchaseOrganisation { get; set; }
        public Nullable<double> MinOrderQuantity { get; set; }
        public string ShelfExpiryLifeUoM { get; set; }
        public Nullable<short> CountryOfOrigin { get; set; }
        public string HSCode { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<byte> LeadTime { get; set; }
        public string LeadTimeUom { get; set; }
        public string ShelfExpiryLife { get; set; }
        public string CurrencyCode { get; set; }
        public string RemainingShelfLife { get; set; }
        public string ManufacturerName { get; set; }
        public Nullable<int> VendorNumber { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public Nullable<bool> IsDefaultVendor { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
    }
}
