//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralItemGeneralData
    {
        public int ID { get; set; }
        public Nullable<short> ManufacturerID { get; set; }
        public Nullable<byte> ShippingTypeID { get; set; }
        public Nullable<byte> SerialAndBatchManagedBy { get; set; }
        public Nullable<byte> ManagementMethod { get; set; }
        public Nullable<byte> IssueMethod { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public Nullable<double> Temprature { get; set; }
        public Nullable<double> NetContentPerPiece { get; set; }
        public Nullable<double> NetWeightPerPiece { get; set; }
        public string NetContentUOM { get; set; }
        public string SpecialFeature { get; set; }
        public string ShortDescription { get; set; }
        public string BrandName { get; set; }
        public string ArabicTransalation { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
    }
}
