//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralTaskReportingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralTaskReportingDetail()
        {
            this.GeneralTaskIntiatedDetails = new HashSet<GeneralTaskIntiatedDetail>();
            this.TaskNotificationDetails = new HashSet<TaskNotificationDetail>();
        }
    
        public int ID { get; set; }
        public int GeneralTaskReportingMasterID { get; set; }
        public int StageSequenceNumber { get; set; }
        public Nullable<int> IsParallel { get; set; }
        public int TaskReportingRoleID { get; set; }
        public Nullable<decimal> RangeFrom { get; set; }
        public Nullable<decimal> RangeUpto { get; set; }
        public string RoleCentreCode { get; set; }
        public Nullable<int> TaskAutoEscalationTime { get; set; }
        public string TaskAutoEscalationFlag { get; set; }
        public string UnitSpan { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsLastStage { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsActiveMember { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralTaskIntiatedDetail> GeneralTaskIntiatedDetails { get; set; }
        public virtual GeneralTaskReportingMaster GeneralTaskReportingMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskNotificationDetail> TaskNotificationDetails { get; set; }
    }
}
