//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralTaxTransaction
    {
        public long ID { get; set; }
        public byte GeneralTaxGroupMasterID { get; set; }
        public long SourceTransactionID { get; set; }
        public int ItemNumber { get; set; }
        public byte TransactionTypeID { get; set; }
        public byte GeneralTaxMasterID { get; set; }
        public Nullable<decimal> CalulatedTaxAmount { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
    }
}
