//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralRunningNumbersForAccount
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string KeyField { get; set; }
        public short FinancialYearID { get; set; }
        public string CentreCode { get; set; }
        public string Prefix { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string DisplayFormat { get; set; }
        public short StartNumber { get; set; }
        public Nullable<int> CurrentCounter { get; set; }
        public string Seperator { get; set; }
        public Nullable<bool> IsLastRecord { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ActSessionMaster ActSessionMaster { get; set; }
    }
}
