//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTEInvoiceMaster
    {
        public int ID { get; set; }
        public int SalesInvoiceMasterID { get; set; }
        public string AcknowledgementNo { get; set; }
        public string AcknowledgementDate { get; set; }
        public string Irn { get; set; }
        public string QrCodeImage { get; set; }
        public bool IsCancelledEInvoice { get; set; }
        public string CancelledEInvoiceDate { get; set; }
        public string CancelledEInvoiceReason { get; set; }
        public string CancelledEInvoiceDescription { get; set; }
    }
}
