//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GymUserTransactionDetail : RARIndiaEntityBaseModel
    {
        public int GymUserTransactionDetailId { get; set; }
        public int GymUserRegistrationId { get; set; }
        public short GymMembershipPlanMasterId { get; set; }
        public short GymPlanDurationMasterId { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal PreLaunchSpecialOfferAmount { get; set; }
        public decimal TotalAmountPaid { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public byte PaymentTypeMasterId { get; set; }
        public string TransactionReference { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
