//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryStockMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryStockMaster()
        {
            this.InventoryTransactionDetails = new HashSet<InventoryTransactionDetail>();
        }
    
        public long Id { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public Nullable<int> GeneralItemCodeID { get; set; }
        public Nullable<short> InventoryLocationMasterId { get; set; }
        public Nullable<double> OpeningBalanceQty { get; set; }
        public Nullable<double> ClosingBalanceQty { get; set; }
        public Nullable<double> CurrentStockQty { get; set; }
        public Nullable<double> DamageStockQty { get; set; }
        public Nullable<double> StolenStockQty { get; set; }
        public Nullable<int> FinancialYearID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTransactionDetail> InventoryTransactionDetails { get; set; }
    }
}
