//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItemStoreLevelSpecificInfo
    {
        public int ID { get; set; }
        public int GeneralItemMasterID { get; set; }
        public short GeneralUnitsID { get; set; }
        public Nullable<byte> RPType { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> RoundingProfile { get; set; }
        public string PlannerCode { get; set; }
        public Nullable<int> OrderingDay { get; set; }
        public Nullable<double> LeadTime { get; set; }
        public string leadTimeUom { get; set; }
        public Nullable<int> DeliveryDay { get; set; }
        public string SupplySource { get; set; }
        public Nullable<bool> BlockforProcurutment { get; set; }
        public Nullable<double> GRProccessingTime { get; set; }
        public string GRPUomCode { get; set; }
        public Nullable<byte> ReorderPoint { get; set; }
        public Nullable<byte> SafetyStockDriven { get; set; }
        public string ShelfNumber { get; set; }
        public Nullable<int> Facing { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
    }
}
