//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryRecipeMaster
    {
        public short ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> PrimaryItemOutputID { get; set; }
        public string VersionCode { get; set; }
        public Nullable<int> OldRecipeID { get; set; }
        public string Definevariants { get; set; }
        public string BOMRelevant { get; set; }
        public string BillingItemName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<byte> RelatedWithCafe { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string ArabicTransalation { get; set; }
        public string RecipeMenuImage { get; set; }
    }
}
