//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItemBatchMaster
    {
        public int ID { get; set; }
        public int ItemNumber { get; set; }
        public string ItemBarCode { get; set; }
        public Nullable<short> InventoryLocationMasterId { get; set; }
        public Nullable<short> BalanceSheetID { get; set; }
        public string PurchaseBillID { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> BatchQuantity { get; set; }
        public Nullable<decimal> SoldQuantity { get; set; }
        public Nullable<bool> IsBatchSold { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsBatchClosed { get; set; }
    }
}
