//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryUoMMaster
    {
        public short ID { get; set; }
        public string UomCode { get; set; }
        public string UoMDescription { get; set; }
        public string CommercialDescription { get; set; }
        public Nullable<short> DimensionUnitMasterID { get; set; }
        public Nullable<double> ConvertionFactor { get; set; }
        public string AdditiveConstant { get; set; }
        public Nullable<byte> DeciamlPlacesUpto { get; set; }
        public Nullable<byte> DecimalRounding { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsAlternativeUom { get; set; }
        public string GSTUnitCode { get; set; }
        public string GSTUnitDescription { get; set; }
    }
}
