//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryPhysicalStockAdjustment
    {
        public int ID { get; set; }
        public int InventoryPhysicalStockAdjustmentMasterID { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public string ItemBarCode { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<byte> Action { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> FromLocation { get; set; }
        public Nullable<double> CurrentStockQty { get; set; }
        public Nullable<bool> IsCurrentStock { get; set; }
        public string OrderUom { get; set; }
        public Nullable<double> ConversionFactor { get; set; }
        public Nullable<int> BatchMasterID { get; set; }
        public string ConsumptionUoM { get; set; }
    }
}
