//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransactionDetail
    {
        public long Id { get; set; }
        public Nullable<long> InventoryStockMasterID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<byte> TransactionTypeId { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<long> StockEffectedID { get; set; }
        public Nullable<double> DamageStockQty { get; set; }
        public Nullable<double> StolenStockQty { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string BaseUOM { get; set; }
        public Nullable<double> TransactionQuantity { get; set; }
        public string TransactionUOM { get; set; }
        public string MovementTypeCode { get; set; }
        public Nullable<double> CurrentStockQty { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> BatchMasterID { get; set; }
    
        public virtual GeneralTransactionMaster GeneralTransactionMaster { get; set; }
        public virtual InventoryStockMaster InventoryStockMaster { get; set; }
    }
}
