//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItemBatchDetail
    {
        public int ID { get; set; }
        public int PuchaseItemBatchMasterId { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> BatchEffectedID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<short> InventoryLocationMasterId { get; set; }
        public string CentreCode { get; set; }
        public Nullable<short> GeneralUnitsID { get; set; }
        public string MovementTypeCode { get; set; }
    }
}
