//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveEmployeeAttendanceDetail
    {
        public long ID { get; set; }
        public Nullable<long> EmployeeAttendanceMasterID { get; set; }
        public Nullable<System.TimeSpan> LoginTime { get; set; }
        public Nullable<System.TimeSpan> LogoutTime { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsLastRecord { get; set; }
    }
}
