//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveEmployeeAttendanceMaster
    {
        public long ID { get; set; }
        public Nullable<long> EmployeeShiftTransactionID { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public Nullable<bool> AttendanceStatus { get; set; }
        public Nullable<byte> OverAllStatus { get; set; }
        public Nullable<int> EmployeeShiftMasterID { get; set; }
        public Nullable<System.TimeSpan> CheckInTime { get; set; }
        public Nullable<System.TimeSpan> CheckOutTime { get; set; }
        public string UserLateRemark { get; set; }
        public string CentreCode { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<byte> PunchingType { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> EmployeeShiftDetailID { get; set; }
        public Nullable<bool> IsLastRecord { get; set; }
        public Nullable<byte> IsInformedLeave { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsEmployeeExmpted { get; set; }
        public Nullable<byte> LateMarkCount { get; set; }
        public Nullable<bool> IsConsiderForLateMark { get; set; }
    }
}
