//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveAttachedDocument
    {
        public long ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> EmployeeDocumentRequiredID { get; set; }
        public Nullable<System.DateTime> DateOfSubmission { get; set; }
        public Nullable<int> LeaveApplicationID { get; set; }
        public string FileName { get; set; }
    }
}
