//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplication
    {
        public long ID { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> LeaveMasterID { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> UptoDate { get; set; }
        public Nullable<short> TotalfullDaysLeave { get; set; }
        public Nullable<short> TotalHalfDayLeave { get; set; }
        public string HalfLeaveStatus { get; set; }
        public string EmployeeRemark { get; set; }
        public Nullable<bool> DocumentRequire { get; set; }
        public string LeaveReason { get; set; }
        public Nullable<byte> LeavePriority { get; set; }
        public string ApplicationStatus { get; set; }
        public Nullable<byte> PendingAtApprovalLevel { get; set; }
        public Nullable<int> LeaveSessionId { get; set; }
        public string CancelRemark { get; set; }
        public Nullable<short> SactionedFullDay { get; set; }
        public Nullable<short> SactionedHalfDay { get; set; }
        public string SactionedHalfLeaveStatus { get; set; }
        public Nullable<decimal> TransferToLWP { get; set; }
        public Nullable<int> ApprovedByUser { get; set; }
        public string CentreCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> LeaveRuleMasterID { get; set; }
        public Nullable<int> PendingJobSrNo { get; set; }
        public Nullable<int> PendingLevelSeqNumber { get; set; }
        public Nullable<int> SancWorkReportingMstID { get; set; }
        public Nullable<int> PendAtWorkReportingDetailID { get; set; }
        public Nullable<System.DateTime> SactionFromDate { get; set; }
        public Nullable<System.DateTime> SactionUptoDate { get; set; }
        public Nullable<int> AdminRoleMasterID { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public Nullable<int> Deletedby { get; set; }
        public Nullable<System.DateTime> Deleteddate { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public Nullable<byte> LeaveApplicationType { get; set; }
    }
}
