//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveApplicationTransaction
    {
        public long ID { get; set; }
        public Nullable<int> LeaveApplicationID { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public Nullable<bool> FullDayHalfDayFlag { get; set; }
        public string HalfLeaveStatus { get; set; }
        public Nullable<int> LeaveAvailedID { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public Nullable<int> Deletedby { get; set; }
        public Nullable<System.DateTime> Deleteddate { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public Nullable<bool> IsAdvancedLeave { get; set; }
    }
}
