//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveSummary
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> LeaveMasterID { get; set; }
        public Nullable<double> BalanceLeave { get; set; }
        public Nullable<int> LeaveRuleMasterId { get; set; }
        public string ReasonForInsertion { get; set; }
        public Nullable<bool> IsCurrentStatus { get; set; }
        public Nullable<int> LeaveSessionID { get; set; }
        public Nullable<decimal> TotalFullDayUtilized { get; set; }
        public Nullable<decimal> TotalHalfDayUtilized { get; set; }
        public string BalanceCarryForwardStatus { get; set; }
        public string CentreCode { get; set; }
        public Nullable<int> SummaryIDBFFrom { get; set; }
        public Nullable<int> SummeryIDCFTo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
