//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTransaction
    {
        public int ID { get; set; }
        public Nullable<byte> NotificationTypeMasterID { get; set; }
        public Nullable<byte> NotificationMediaMasterID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<byte> AutoExpiryInDays { get; set; }
        public Nullable<int> FromUserID { get; set; }
        public Nullable<int> ToUserID { get; set; }
        public string SubjectDescription { get; set; }
        public string BodyDescription { get; set; }
        public string FromMailID { get; set; }
        public string ToMailID { get; set; }
        public Nullable<byte> Status { get; set; }
        public string FromContactNumber { get; set; }
        public string ToContactNumber { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
    }
}
