//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganisationMaster : RARIndiaEntityBaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrganisationMaster()
        {
            this.OrganisationCentreMasters = new HashSet<OrganisationCentreMaster>();
        }
    
        public byte OrganisationMasterId { get; set; }
        public string EstablishmentCode { get; set; }
        public string OrganisationName { get; set; }
        public System.DateTime FoundationDatetime { get; set; }
        public string FounderMember { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PlotNumber { get; set; }
        public string StreetNumber { get; set; }
        public int LocationId { get; set; }
        public string Pincode { get; set; }
        public string EmailId { get; set; }
        public string Url { get; set; }
        public string OfficeComment { get; set; }
        public string MissionStatement { get; set; }
        public string MobileNumber { get; set; }
        public string FaxNumber { get; set; }
        public string OfficePhone1 { get; set; }
        public string OfficePhone2 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string OrganisationCode { get; set; }
        public string PFNumber { get; set; }
        public string ESICNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganisationCentreMaster> OrganisationCentreMasters { get; set; }
    }
}
