//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganisationCentrewiseGSTCredential
    {
        public int ID { get; set; }
        public string CentreCode { get; set; }
        public string Version { get; set; }
        public string Urls { get; set; }
        public string EInvoiceUserName { get; set; }
        public string EInvoicePassword { get; set; }
        public string AspId { get; set; }
        public string AspUserPassword { get; set; }
        public Nullable<int> QrCodeSize { get; set; }
        public string AuthToken { get; set; }
        public string TokenExpiry { get; set; }
        public string ClientId { get; set; }
        public bool IsLiveMode { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
