//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganisationUniversityMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrganisationUniversityMaster()
        {
            this.OrganisationStudyCentreUniversityApplicables = new HashSet<OrganisationStudyCentreUniversityApplicable>();
        }
    
        public short ID { get; set; }
        public string UniversityName { get; set; }
        public string EstablishmentCode { get; set; }
        public Nullable<System.DateTime> UniversityFoundationDatetime { get; set; }
        public string UniversityFounderMember { get; set; }
        public string UniversityAddress1 { get; set; }
        public string UniversityAddress2 { get; set; }
        public string PlotNumber { get; set; }
        public string StreetNumber { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Pincode { get; set; }
        public string FaxNumber { get; set; }
        public string PhoneNumberOffice { get; set; }
        public string Extention { get; set; }
        public string CellPhone { get; set; }
        public string EmailID { get; set; }
        public string Url { get; set; }
        public string OfficeComment { get; set; }
        public string MissionStatement { get; set; }
        public Nullable<bool> DefaultFlag { get; set; }
        public string UniversityReportPath { get; set; }
        public string UniversityShortName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganisationStudyCentreUniversityApplicable> OrganisationStudyCentreUniversityApplicables { get; set; }
    }
}
