//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using RARIndia.Model;

    using System;

    public partial class OrganisationCentrewiseDepartmentDomain : RARIndiaEntityBaseModel
    {
        public short ID { get; set; }
        public byte AdminRoleDomainID { get; set; }
        public short OrganisationCentrewiseDepartmentID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
