//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFChalanRemitance
    {
        public long ID { get; set; }
        public Nullable<byte> Month { get; set; }
        public string Year { get; set; }
        public Nullable<byte> PaymentMode { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<decimal> EmployeeShare { get; set; }
        public Nullable<decimal> EmployerAcc01 { get; set; }
        public Nullable<decimal> EmployerAcc02 { get; set; }
        public Nullable<decimal> EmployerAcc10 { get; set; }
        public Nullable<decimal> EmployerAcc21 { get; set; }
        public Nullable<decimal> EmployerAcc22 { get; set; }
        public Nullable<decimal> TotalAmountRemited { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> ChallanRemmittanceDate { get; set; }
    }
}
