//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseGRNDetail
    {
        public int ID { get; set; }
        public int PurchaseGRNMasterID { get; set; }
        public Nullable<double> ReceivedQuantity { get; set; }
        public int ReceivingLocationID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string Remark { get; set; }
        public Nullable<int> GeneralItemCodeID { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public string BarCode { get; set; }
        public string OrderUomCode { get; set; }
        public Nullable<double> BaseUOMQuantity { get; set; }
        public string BaseUOMCode { get; set; }
        public Nullable<decimal> DamagedQuantity { get; set; }
        public Nullable<short> LocationID { get; set; }
        public Nullable<bool> FOC { get; set; }
        public Nullable<decimal> FocReceivedQuantity { get; set; }
    
        public virtual InventoryLocationMaster InventoryLocationMaster { get; set; }
    }
}
