//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoiceDetail
    {
        public long ID { get; set; }
        public long PurchaseVendorInvoiceMasterID { get; set; }
        public int GeneralItemCodeID { get; set; }
        public int ItemNumber { get; set; }
        public string OrderUomCode { get; set; }
        public int InvoiceQuantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<byte> GeneralTaxGroupMasterID { get; set; }
    
        public virtual GeneralItemCode GeneralItemCode { get; set; }
        public virtual PurchaseInvoiceMaster PurchaseInvoiceMaster { get; set; }
    }
}
