//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReturnMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseReturnMaster()
        {
            this.PurchaseReturnTransactions = new HashSet<PurchaseReturnTransaction>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> TotalTaxAmount { get; set; }
        public Nullable<decimal> RoundUpAmount { get; set; }
        public Nullable<decimal> PurchaseReturnAmount { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<short> BalanceSheetID { get; set; }
        public string PurchaseReturnNumber { get; set; }
        public Nullable<short> LocationID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ActBalsheetMaster ActBalsheetMaster { get; set; }
        public virtual GeneralSupplierMaster GeneralSupplierMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseReturnTransaction> PurchaseReturnTransactions { get; set; }
    }
}
