//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoiceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseInvoiceMaster()
        {
            this.PurchaseInvoiceDetails = new HashSet<PurchaseInvoiceDetail>();
        }
    
        public long ID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string VendorInvoiceNumber { get; set; }
        public int VendorId { get; set; }
        public int PurchaseOrderMasterID { get; set; }
        public long PurchaseVendorInvoiceMasterID { get; set; }
        public Nullable<decimal> TotalIInvoiceAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<int> StorageLocationID { get; set; }
        public Nullable<decimal> RoundUpAmount { get; set; }
        public Nullable<short> BalanceSheetID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> InvoicePaidAmount { get; set; }
        public Nullable<byte> InvoiceStatusFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }
        public virtual PurchaseOrderMaster PurchaseOrderMaster { get; set; }
    }
}
