//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequisitionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseRequisitionMaster()
        {
            this.PurchaseOrderMasters = new HashSet<PurchaseOrderMaster>();
            this.PurchaseRequisitionDetails = new HashSet<PurchaseRequisitionDetail>();
        }
    
        public int ID { get; set; }
        public string PurchaseRequisitionNumber { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<byte> PurchaseRequisitionType { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<bool> IsOpenForPO { get; set; }
        public Nullable<byte> PRStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string PurchaseRequisitionBehaviour { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> ShippingHandling { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TradeIn { get; set; }
        public Nullable<decimal> TotalTaxAmount { get; set; }
        public Nullable<byte> POStatus { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        public virtual GeneralSupplierMaster GeneralSupplierMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderMaster> PurchaseOrderMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRequisitionDetail> PurchaseRequisitionDetails { get; set; }
    }
}
