//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public int ID { get; set; }
        public Nullable<int> PurchaseRequisitionDetailsID { get; set; }
        public Nullable<int> PurchaseOrderMasterID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> StorageLocationID { get; set; }
        public Nullable<int> IssueFromLocationID { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public Nullable<byte> PriorityFlag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> GeneralItemCodeID { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public string BarCode { get; set; }
        public string UomCode { get; set; }
        public string OrderUomCode { get; set; }
        public Nullable<double> BaseUOMQuantity { get; set; }
        public string BaseUOMCode { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<byte> GeneralTaxGroupMasterID { get; set; }
    
        public virtual PurchaseOrderMaster PurchaseOrderMaster { get; set; }
    }
}
