//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReturnTransaction
    {
        public long ID { get; set; }
        public Nullable<int> PurchaseReturnMasterId { get; set; }
        public string ItemNumber { get; set; }
        public Nullable<byte> TaxAmount { get; set; }
        public Nullable<byte> GenTaxGroupMasterID { get; set; }
        public Nullable<int> TaxInPercentage { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string UOMCode { get; set; }
        public Nullable<int> GeneralItemCodeID { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string PurchaseGrnNumber { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual GeneralItemCode GeneralItemCode { get; set; }
        public virtual GeneralTaxGroupMaster GeneralTaxGroupMaster { get; set; }
        public virtual PurchaseReturnMaster PurchaseReturnMaster { get; set; }
    }
}
