//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequirementDetail
    {
        public int ID { get; set; }
        public Nullable<int> PurchaseRequirementMasterID { get; set; }
        public Nullable<int> GeneralItemCodeID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string CentreCode { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> StorageLocationID { get; set; }
        public Nullable<byte> PriorityFlag { get; set; }
        public Nullable<byte> ApprovedStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<decimal> ApprovedQuantity { get; set; }
        public Nullable<decimal> DeliveredQuantity { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public string BarCode { get; set; }
        public string UomCode { get; set; }
        public Nullable<decimal> PurchaseRequisitionQuantity { get; set; }
        public Nullable<byte> PurchaseRequisitionStatus { get; set; }
        public Nullable<int> CustomerBranchMasterID { get; set; }
        public string CustomerBranchName { get; set; }
        public Nullable<int> SalesOrderDetailsID { get; set; }
    
        public virtual PurchaseRequirementMaster PurchaseRequirementMaster { get; set; }
    }
}
