//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ver1Entities : DbContext
    {
        public Ver1Entities()
            : base("name=Ver1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActAccountCenterwise> ActAccountCenterwises { get; set; }
        public virtual DbSet<ActAccountMaster> ActAccountMasters { get; set; }
        public virtual DbSet<ActBalsheetMaster> ActBalsheetMasters { get; set; }
        public virtual DbSet<ActBalsheetTypeMaster> ActBalsheetTypeMasters { get; set; }
        public virtual DbSet<ActBankDetail> ActBankDetails { get; set; }
        public virtual DbSet<ActBankTransaction> ActBankTransactions { get; set; }
        public virtual DbSet<ActCategoryMaster> ActCategoryMasters { get; set; }
        public virtual DbSet<ActCentreOpeningBalance> ActCentreOpeningBalances { get; set; }
        public virtual DbSet<ActChequeBookDetail> ActChequeBookDetails { get; set; }
        public virtual DbSet<ActChequeBookMaster> ActChequeBookMasters { get; set; }
        public virtual DbSet<ActGeneralSettingMaster> ActGeneralSettingMasters { get; set; }
        public virtual DbSet<ActGroupMaster> ActGroupMasters { get; set; }
        public virtual DbSet<ActHeadMaster> ActHeadMasters { get; set; }
        public virtual DbSet<ActIndividualOpeningBalance> ActIndividualOpeningBalances { get; set; }
        public virtual DbSet<ActNarrationMaster> ActNarrationMasters { get; set; }
        public virtual DbSet<ActSessionMaster> ActSessionMasters { get; set; }
        public virtual DbSet<ActTransactionDetail> ActTransactionDetails { get; set; }
        public virtual DbSet<ActTransactionMaster> ActTransactionMasters { get; set; }
        public virtual DbSet<ActTransactionTypeMaster> ActTransactionTypeMasters { get; set; }
        public virtual DbSet<ActVoucherSettingMaster> ActVoucherSettingMasters { get; set; }
        public virtual DbSet<AdminRoleApplicableDetail> AdminRoleApplicableDetails { get; set; }
        public virtual DbSet<AdminRoleCentreRight> AdminRoleCentreRights { get; set; }
        public virtual DbSet<AdminRoleDomain> AdminRoleDomains { get; set; }
        public virtual DbSet<AdminRoleEntity> AdminRoleEntities { get; set; }
        public virtual DbSet<AdminRoleMaster> AdminRoleMasters { get; set; }
        public virtual DbSet<AdminRoleMenuDetail> AdminRoleMenuDetails { get; set; }
        public virtual DbSet<AdminRoleRightType> AdminRoleRightTypes { get; set; }
        public virtual DbSet<AdminRoleSpecialRightDetail> AdminRoleSpecialRightDetails { get; set; }
        public virtual DbSet<AdminRoleSpecialRightMaster> AdminRoleSpecialRightMasters { get; set; }
        public virtual DbSet<AdminSnPost> AdminSnPosts { get; set; }
        public virtual DbSet<BankMaster> BankMasters { get; set; }
        public virtual DbSet<CustomerBranchMaster> CustomerBranchMasters { get; set; }
        public virtual DbSet<CustomerContactDetail> CustomerContactDetails { get; set; }
        public virtual DbSet<CustomerMaster> CustomerMasters { get; set; }
        public virtual DbSet<DashboardAllocation> DashboardAllocations { get; set; }
        public virtual DbSet<DashboardContentDetail> DashboardContentDetails { get; set; }
        public virtual DbSet<EmployeeContactDetail> EmployeeContactDetails { get; set; }
        public virtual DbSet<EmployeeDesignationMaster> EmployeeDesignationMasters { get; set; }
        public virtual DbSet<EmployeeExperience> EmployeeExperiences { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
        public virtual DbSet<EmployeePictureDetail> EmployeePictureDetails { get; set; }
        public virtual DbSet<EmployeeQualification> EmployeeQualifications { get; set; }
        public virtual DbSet<EmployeeServiceDetail> EmployeeServiceDetails { get; set; }
        public virtual DbSet<EmployeeShiftMaster> EmployeeShiftMasters { get; set; }
        public virtual DbSet<ESICZoneDetail> ESICZoneDetails { get; set; }
        public virtual DbSet<ESICZoneMaster> ESICZoneMasters { get; set; }
        public virtual DbSet<GeneralAllocateSaleProcessUnit> GeneralAllocateSaleProcessUnits { get; set; }
        public virtual DbSet<GeneralCity> GeneralCities { get; set; }
        public virtual DbSet<GeneralCountryMaster> GeneralCountryMasters { get; set; }
        public virtual DbSet<GeneralCurrencyMaster> GeneralCurrencyMasters { get; set; }
        public virtual DbSet<GeneralDepartmentMaster> GeneralDepartmentMasters { get; set; }
        public virtual DbSet<GeneralEducationMaster> GeneralEducationMasters { get; set; }
        public virtual DbSet<GeneralEducationTypeMaster> GeneralEducationTypeMasters { get; set; }
        public virtual DbSet<GeneralExperienceTypeMaster> GeneralExperienceTypeMasters { get; set; }
        public virtual DbSet<GeneralItemAttributeData> GeneralItemAttributeDatas { get; set; }
        public virtual DbSet<GeneralItemCategoryMaster> GeneralItemCategoryMasters { get; set; }
        public virtual DbSet<GeneralItemCode> GeneralItemCodes { get; set; }
        public virtual DbSet<GeneralItemGeneralData> GeneralItemGeneralDatas { get; set; }
        public virtual DbSet<GeneralItemMarchandiseBaseCatgory> GeneralItemMarchandiseBaseCatgories { get; set; }
        public virtual DbSet<GeneralItemMarchandiseGroup> GeneralItemMarchandiseGroups { get; set; }
        public virtual DbSet<GeneralItemMarchandiseSubCategory> GeneralItemMarchandiseSubCategories { get; set; }
        public virtual DbSet<GeneralItemMaster> GeneralItemMasters { get; set; }
        public virtual DbSet<GeneralItemMerchantiseCategory> GeneralItemMerchantiseCategories { get; set; }
        public virtual DbSet<GeneralItemMerchantiseDepartment> GeneralItemMerchantiseDepartments { get; set; }
        public virtual DbSet<GeneralItemSupliersData> GeneralItemSupliersDatas { get; set; }
        public virtual DbSet<GeneralJobProfile> GeneralJobProfiles { get; set; }
        public virtual DbSet<GeneralJobStatu> GeneralJobStatus { get; set; }
        public virtual DbSet<GeneralLevelMaster> GeneralLevelMasters { get; set; }
        public virtual DbSet<GeneralLocationMaster> GeneralLocationMasters { get; set; }
        public virtual DbSet<GeneralMapTypeOfAccount> GeneralMapTypeOfAccounts { get; set; }
        public virtual DbSet<GeneralMovementType> GeneralMovementTypes { get; set; }
        public virtual DbSet<GeneralMovementTypeRule> GeneralMovementTypeRules { get; set; }
        public virtual DbSet<GeneralNationalityMaster> GeneralNationalityMasters { get; set; }
        public virtual DbSet<GeneralOrderingDaysCode> GeneralOrderingDaysCodes { get; set; }
        public virtual DbSet<GeneralPeriodTypeMaster> GeneralPeriodTypeMasters { get; set; }
        public virtual DbSet<GeneralPolicyDetail> GeneralPolicyDetails { get; set; }
        public virtual DbSet<GeneralPolicyMaster> GeneralPolicyMasters { get; set; }
        public virtual DbSet<GeneralPolicyRule> GeneralPolicyRules { get; set; }
        public virtual DbSet<GeneralPurchaseGroupMaster> GeneralPurchaseGroupMasters { get; set; }
        public virtual DbSet<GeneralReccessMaster> GeneralReccessMasters { get; set; }
        public virtual DbSet<GeneralRegionMaster> GeneralRegionMasters { get; set; }
        public virtual DbSet<GeneralRelationshipTypeMaster> GeneralRelationshipTypeMasters { get; set; }
        public virtual DbSet<GeneralRequestMaster> GeneralRequestMasters { get; set; }
        public virtual DbSet<GeneralRequestTransaction> GeneralRequestTransactions { get; set; }
        public virtual DbSet<GeneralRunningNumbersForAccount> GeneralRunningNumbersForAccounts { get; set; }
        public virtual DbSet<GeneralSectorType> GeneralSectorTypes { get; set; }
        public virtual DbSet<GeneralSessionMaster> GeneralSessionMasters { get; set; }
        public virtual DbSet<GeneralShipperMaster> GeneralShipperMasters { get; set; }
        public virtual DbSet<GeneralSupplierMaster> GeneralSupplierMasters { get; set; }
        public virtual DbSet<GeneralSystemSettingMaster> GeneralSystemSettingMasters { get; set; }
        public virtual DbSet<GeneralTaskModel> GeneralTaskModels { get; set; }
        public virtual DbSet<GeneralTaskReportingDetail> GeneralTaskReportingDetails { get; set; }
        public virtual DbSet<GeneralTaskReportingMaster> GeneralTaskReportingMasters { get; set; }
        public virtual DbSet<GeneralTaxGroupMaster> GeneralTaxGroupMasters { get; set; }
        public virtual DbSet<GeneralTaxGroupMasterDetail> GeneralTaxGroupMasterDetails { get; set; }
        public virtual DbSet<GeneralTaxMaster> GeneralTaxMasters { get; set; }
        public virtual DbSet<GeneralTaxTransaction> GeneralTaxTransactions { get; set; }
        public virtual DbSet<GeneralTemperatureMaster> GeneralTemperatureMasters { get; set; }
        public virtual DbSet<GeneralTimeZoneMaster> GeneralTimeZoneMasters { get; set; }
        public virtual DbSet<GeneralTitleMaster> GeneralTitleMasters { get; set; }
        public virtual DbSet<GeneralTransactionMaster> GeneralTransactionMasters { get; set; }
        public virtual DbSet<GeneralTypeOfAccount> GeneralTypeOfAccounts { get; set; }
        public virtual DbSet<GeneralTypeOfAccountMapWithAccount> GeneralTypeOfAccountMapWithAccounts { get; set; }
        public virtual DbSet<GeneralUnitMaster> GeneralUnitMasters { get; set; }
        public virtual DbSet<GeneralUnit> GeneralUnits { get; set; }
        public virtual DbSet<GeneralUnitsDomainRelated> GeneralUnitsDomainRelateds { get; set; }
        public virtual DbSet<GeneralUnitsStorageLocation> GeneralUnitsStorageLocations { get; set; }
        public virtual DbSet<GeneralUnitType> GeneralUnitTypes { get; set; }
        public virtual DbSet<GeneralWeekDay> GeneralWeekDays { get; set; }
        public virtual DbSet<GenLanguageMaster> GenLanguageMasters { get; set; }
        public virtual DbSet<GSTEInvoiceDetail> GSTEInvoiceDetails { get; set; }
        public virtual DbSet<InventoryAttributeMaster> InventoryAttributeMasters { get; set; }
        public virtual DbSet<InventoryBrandMaster> InventoryBrandMasters { get; set; }
        public virtual DbSet<InventoryItemBatchDetail> InventoryItemBatchDetails { get; set; }
        public virtual DbSet<InventoryItemBatchMaster> InventoryItemBatchMasters { get; set; }
        public virtual DbSet<InventoryItemCodeUnitLevelCustomerSpecificInfo> InventoryItemCodeUnitLevelCustomerSpecificInfoes { get; set; }
        public virtual DbSet<InventoryItemCodeUnitLevelSpecificInfo> InventoryItemCodeUnitLevelSpecificInfoes { get; set; }
        public virtual DbSet<InventoryItemStoreLevelSpecificInfo> InventoryItemStoreLevelSpecificInfoes { get; set; }
        public virtual DbSet<InventoryItemStoreSpecificInfo> InventoryItemStoreSpecificInfoes { get; set; }
        public virtual DbSet<InventoryLocationMaster> InventoryLocationMasters { get; set; }
        public virtual DbSet<InventoryPhysicalStockAdjustment> InventoryPhysicalStockAdjustments { get; set; }
        public virtual DbSet<InventoryPhysicalStockAdjustmentMaster> InventoryPhysicalStockAdjustmentMasters { get; set; }
        public virtual DbSet<InventoryRecipeMaster> InventoryRecipeMasters { get; set; }
        public virtual DbSet<InventoryStockMaster> InventoryStockMasters { get; set; }
        public virtual DbSet<InventoryTransactionDetail> InventoryTransactionDetails { get; set; }
        public virtual DbSet<InventoryUoMMaster> InventoryUoMMasters { get; set; }
        public virtual DbSet<InvoiceTrackingDetail> InvoiceTrackingDetails { get; set; }
        public virtual DbSet<InvoiceTrackingMaster> InvoiceTrackingMasters { get; set; }
        public virtual DbSet<LeaveApplication> LeaveApplications { get; set; }
        public virtual DbSet<LeaveApplicationTransaction> LeaveApplicationTransactions { get; set; }
        public virtual DbSet<LeaveApplicationTransactionHistory> LeaveApplicationTransactionHistories { get; set; }
        public virtual DbSet<LeaveAttachedDocument> LeaveAttachedDocuments { get; set; }
        public virtual DbSet<LeaveAttendanceExemption> LeaveAttendanceExemptions { get; set; }
        public virtual DbSet<LeaveEmployeeAttendanceDetail> LeaveEmployeeAttendanceDetails { get; set; }
        public virtual DbSet<LeaveEmployeeAttendanceFireHistory> LeaveEmployeeAttendanceFireHistories { get; set; }
        public virtual DbSet<LeaveEmployeeAttendanceMaster> LeaveEmployeeAttendanceMasters { get; set; }
        public virtual DbSet<LeaveSummary> LeaveSummaries { get; set; }
        public virtual DbSet<NotificationTransaction> NotificationTransactions { get; set; }
        public virtual DbSet<OrganisationCentrewiseDepartment> OrganisationCentrewiseDepartments { get; set; }
        public virtual DbSet<OrganisationCentrewiseDepartmentDomain> OrganisationCentrewiseDepartmentDomains { get; set; }
        public virtual DbSet<OrganisationCentrewiseGSTCredential> OrganisationCentrewiseGSTCredentials { get; set; }
        public virtual DbSet<OrganisationMaster> OrganisationMasters { get; set; }
        public virtual DbSet<OrganisationStudyCentreMaster> OrganisationStudyCentreMasters { get; set; }
        public virtual DbSet<OrganisationStudyCentrePrintingFormat> OrganisationStudyCentrePrintingFormats { get; set; }
        public virtual DbSet<OrganisationStudyCentreUniversityApplicable> OrganisationStudyCentreUniversityApplicables { get; set; }
        public virtual DbSet<OrganisationUniversityMaster> OrganisationUniversityMasters { get; set; }
        public virtual DbSet<OrgApplicationAdminMaster> OrgApplicationAdminMasters { get; set; }
        public virtual DbSet<OrgCentrewiseSession> OrgCentrewiseSessions { get; set; }
        public virtual DbSet<PFChalanRemitance> PFChalanRemitances { get; set; }
        public virtual DbSet<PurchaseGRNDetail> PurchaseGRNDetails { get; set; }
        public virtual DbSet<PurchaseGRNMaster> PurchaseGRNMasters { get; set; }
        public virtual DbSet<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }
        public virtual DbSet<PurchaseInvoiceMaster> PurchaseInvoiceMasters { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual DbSet<PurchaseOrderMaster> PurchaseOrderMasters { get; set; }
        public virtual DbSet<PurchaseRequirementDetail> PurchaseRequirementDetails { get; set; }
        public virtual DbSet<PurchaseRequirementMaster> PurchaseRequirementMasters { get; set; }
        public virtual DbSet<PurchaseRequisitionDetail> PurchaseRequisitionDetails { get; set; }
        public virtual DbSet<PurchaseRequisitionMaster> PurchaseRequisitionMasters { get; set; }
        public virtual DbSet<PurchaseReturnMaster> PurchaseReturnMasters { get; set; }
        public virtual DbSet<PurchaseReturnTransaction> PurchaseReturnTransactions { get; set; }
        public virtual DbSet<SalaryAllowanceMaster> SalaryAllowanceMasters { get; set; }
        public virtual DbSet<SalaryAllowanceRule> SalaryAllowanceRules { get; set; }
        public virtual DbSet<SalaryAllowanceSumOf> SalaryAllowanceSumOfs { get; set; }
        public virtual DbSet<SalaryDeductionMaster> SalaryDeductionMasters { get; set; }
        public virtual DbSet<SalaryDeductionRule> SalaryDeductionRules { get; set; }
        public virtual DbSet<SalaryDeductionSumOf> SalaryDeductionSumOfs { get; set; }
        public virtual DbSet<SaleContractArrearsAttendance> SaleContractArrearsAttendances { get; set; }
        public virtual DbSet<SaleContractAttendance> SaleContractAttendances { get; set; }
        public virtual DbSet<SaleContractBillingSpan> SaleContractBillingSpans { get; set; }
        public virtual DbSet<SaleContractBillingTransaction> SaleContractBillingTransactions { get; set; }
        public virtual DbSet<SaleContractBillingTransactionLog> SaleContractBillingTransactionLogs { get; set; }
        public virtual DbSet<SaleContractEmployeeAdvance> SaleContractEmployeeAdvances { get; set; }
        public virtual DbSet<SaleContractEmployeeHistory> SaleContractEmployeeHistories { get; set; }
        public virtual DbSet<SaleContractEmployeeMaster> SaleContractEmployeeMasters { get; set; }
        public virtual DbSet<SaleContractExtendedHistory> SaleContractExtendedHistories { get; set; }
        public virtual DbSet<SaleContractFixAttendance> SaleContractFixAttendances { get; set; }
        public virtual DbSet<SaleContractFixItem> SaleContractFixItems { get; set; }
        public virtual DbSet<SaleContractFixItemRate> SaleContractFixItemRates { get; set; }
        public virtual DbSet<SaleContractJobWorkData> SaleContractJobWorkDatas { get; set; }
        public virtual DbSet<SaleContractJobWorkItem> SaleContractJobWorkItems { get; set; }
        public virtual DbSet<SaleContractMachineAssign> SaleContractMachineAssigns { get; set; }
        public virtual DbSet<SaleContractMachineAttendance> SaleContractMachineAttendances { get; set; }
        public virtual DbSet<SaleContractMachineMaster> SaleContractMachineMasters { get; set; }
        public virtual DbSet<SaleContractManPowerAllowance> SaleContractManPowerAllowances { get; set; }
        public virtual DbSet<SaleContractManPowerAllowanceSumOf> SaleContractManPowerAllowanceSumOfs { get; set; }
        public virtual DbSet<SaleContractManPowerAssign> SaleContractManPowerAssigns { get; set; }
        public virtual DbSet<SaleContractManPowerDeduction> SaleContractManPowerDeductions { get; set; }
        public virtual DbSet<SaleContractManPowerDeductionSumOf> SaleContractManPowerDeductionSumOfs { get; set; }
        public virtual DbSet<SaleContractManPowerItem> SaleContractManPowerItems { get; set; }
        public virtual DbSet<SaleContractMaster> SaleContractMasters { get; set; }
        public virtual DbSet<SaleContractOperationalManagerHistory> SaleContractOperationalManagerHistories { get; set; }
        public virtual DbSet<SaleContractOvertime> SaleContractOvertimes { get; set; }
        public virtual DbSet<SaleContractOvertimeSumOf> SaleContractOvertimeSumOfs { get; set; }
        public virtual DbSet<SaleContractRequiredType> SaleContractRequiredTypes { get; set; }
        public virtual DbSet<SaleContractRequirementDetail> SaleContractRequirementDetails { get; set; }
        public virtual DbSet<SaleContractRequirementDetailsHistory> SaleContractRequirementDetailsHistories { get; set; }
        public virtual DbSet<SaleContractSalaryTransaction> SaleContractSalaryTransactions { get; set; }
        public virtual DbSet<SaleContractSalaryTransactionDetail> SaleContractSalaryTransactionDetails { get; set; }
        public virtual DbSet<SaleContractServiceChargeOnManPowerItem> SaleContractServiceChargeOnManPowerItems { get; set; }
        public virtual DbSet<SaleContractServiceChargeOnSalaryHead> SaleContractServiceChargeOnSalaryHeads { get; set; }
        public virtual DbSet<SaleContractServiceItemAttendance> SaleContractServiceItemAttendances { get; set; }
        public virtual DbSet<SaleContractTermDetail> SaleContractTermDetails { get; set; }
        public virtual DbSet<SaleEnquiryDetail> SaleEnquiryDetails { get; set; }
        public virtual DbSet<SaleQuotationDetail> SaleQuotationDetails { get; set; }
        public virtual DbSet<SalesEnquiryMaster> SalesEnquiryMasters { get; set; }
        public virtual DbSet<SalesInvoiceDetail> SalesInvoiceDetails { get; set; }
        public virtual DbSet<SalesInvoiceMaster> SalesInvoiceMasters { get; set; }
        public virtual DbSet<SalesInvoicePendingNotiAccEffect> SalesInvoicePendingNotiAccEffects { get; set; }
        public virtual DbSet<SalesOrderDeliveryDetail> SalesOrderDeliveryDetails { get; set; }
        public virtual DbSet<SalesOrderDeliveryMaster> SalesOrderDeliveryMasters { get; set; }
        public virtual DbSet<SalesOrderDetail> SalesOrderDetails { get; set; }
        public virtual DbSet<SalesOrderMaster> SalesOrderMasters { get; set; }
        public virtual DbSet<SalesQuotationMaster> SalesQuotationMasters { get; set; }
        public virtual DbSet<TaskApprovalFormFieldNameDetail> TaskApprovalFormFieldNameDetails { get; set; }
        public virtual DbSet<TaskApprovalFormFieldNameMaster> TaskApprovalFormFieldNameMasters { get; set; }
        public virtual DbSet<TaskNotificationDetail> TaskNotificationDetails { get; set; }
        public virtual DbSet<TaskNotificationMaster> TaskNotificationMasters { get; set; }
        public virtual DbSet<TempSaleContractBillingTransaction> TempSaleContractBillingTransactions { get; set; }
        public virtual DbSet<TempSaleContractSalaryTransaction> TempSaleContractSalaryTransactions { get; set; }
        public virtual DbSet<TempSaleContractSalaryTransactionDetail> TempSaleContractSalaryTransactionDetails { get; set; }
        public virtual DbSet<TempSalesInvoiceDetail> TempSalesInvoiceDetails { get; set; }
        public virtual DbSet<TempSalesInvoiceMaster> TempSalesInvoiceMasters { get; set; }
        public virtual DbSet<UserDefinedSequenceDetail> UserDefinedSequenceDetails { get; set; }
        public virtual DbSet<UserLock> UserLocks { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<UserLog1> UserLogs1 { get; set; }
        public virtual DbSet<UserMainMenuMaster> UserMainMenuMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserModuleMaster> UserModuleMasters { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<VendorContactPersonInfo> VendorContactPersonInfoes { get; set; }
        public virtual DbSet<VendorFinanceDetail> VendorFinanceDetails { get; set; }
        public virtual DbSet<VendorReplenishmentInfo> VendorReplenishmentInfoes { get; set; }
        public virtual DbSet<GeneralTaskIntiatedDetail> GeneralTaskIntiatedDetails { get; set; }
        public virtual DbSet<GSTEInvoiceMaster> GSTEInvoiceMasters { get; set; }
        public virtual DbSet<UserNotificationCount> UserNotificationCounts { get; set; }
    }
}
