//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleContractBillingSpan
    {
        public long ID { get; set; }
        public Nullable<int> CustomerMasterID { get; set; }
        public Nullable<int> CustomerBranchMasterID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsEmployeeSalaryGenerated { get; set; }
        public Nullable<bool> IsBillGenerated { get; set; }
        public Nullable<decimal> TotalBillAmount { get; set; }
        public Nullable<decimal> RoundOffAmount { get; set; }
        public Nullable<bool> IsMaterialDeliveryCreated { get; set; }
        public Nullable<bool> IsMaterialDeliveryRecived { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> SaleContractMasterID { get; set; }
        public Nullable<int> SalesInvoiceMasterID { get; set; }
        public Nullable<byte> IsBillPaid { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> TDSDeducted { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<bool> IsArrearsCalculated { get; set; }
        public Nullable<int> ArrearsSalesInvoiceMasterID { get; set; }
        public Nullable<int> TempSalesInvoiceMasterID { get; set; }
    }
}
