//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleContractTermDetail
    {
        public long ID { get; set; }
        public Nullable<long> SaleContractMasterID { get; set; }
        public Nullable<byte> BillingCycleInDays { get; set; }
        public Nullable<byte> MaterialSupplyDay { get; set; }
        public Nullable<byte> RenewCallBeforeDays { get; set; }
        public Nullable<decimal> MaterialSupplyFixAmount { get; set; }
        public Nullable<byte> SalarySpanStartDay { get; set; }
        public Nullable<byte> SalarySpanUptoDay { get; set; }
        public Nullable<bool> IsInclusiveServiceCharges { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> SalaryEffectiveFromDate { get; set; }
        public Nullable<double> ServiceChargesPercentage { get; set; }
        public Nullable<byte> ServiceChargesDependOn { get; set; }
        public Nullable<byte> AdditionalAllowancePaidBy { get; set; }
        public Nullable<byte> ServiceChargesCalculateOn { get; set; }
        public Nullable<byte> OverTimeDependOn { get; set; }
        public Nullable<bool> IsServiceChargesAppliedToAddAmount { get; set; }
        public Nullable<byte> OverTimeDisplayFormat { get; set; }
        public Nullable<bool> IsServiceChargesAppliedToServiceItem { get; set; }
        public Nullable<bool> IsServiceChargesAppliedToOverTime { get; set; }
        public Nullable<bool> IsRateFixedForRateContract { get; set; }
        public Nullable<System.DateTime> SalaryEffectiveUptoDate { get; set; }
    
        public virtual SaleContractMaster SaleContractMaster { get; set; }
    }
}
