//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoiceDetail
    {
        public int ID { get; set; }
        public Nullable<int> SalesInvoiceMasterID { get; set; }
        public Nullable<int> GeneralItemCodeID { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public string SaleUomCode { get; set; }
        public Nullable<decimal> InvoiceQuantity { get; set; }
        public Nullable<double> Rate { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<int> GenTaxGroupMasterID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CustomerBranchMasterID { get; set; }
        public Nullable<int> ContactPersonID { get; set; }
        public Nullable<int> GeneralUnitsID { get; set; }
        public Nullable<int> SalesOrderDeliveryMasterID { get; set; }
        public Nullable<int> VariationMasterID { get; set; }
        public string VariationMasterName { get; set; }
        public string BillingDisplayName { get; set; }
        public string DisplayUOMCode { get; set; }
        public Nullable<decimal> DisplayRate { get; set; }
    
        public virtual SalesInvoiceMaster SalesInvoiceMaster { get; set; }
    }
}
