//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleContractRequirementDetail
    {
        public long ID { get; set; }
        public Nullable<long> SaleContractMasterID { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<double> Days { get; set; }
        public Nullable<int> GeneralSiftMasterID { get; set; }
        public Nullable<byte> SaleContractRequiredTypeID { get; set; }
        public Nullable<byte> AssignStatus { get; set; }
        public Nullable<byte> MaterialSupplyStaus { get; set; }
        public Nullable<System.DateTime> MaterialSupplyLastDate { get; set; }
        public Nullable<int> SaleContractManPowerItemID { get; set; }
        public Nullable<double> ActualAssignQuantity { get; set; }
        public Nullable<int> SaleContractJobWorkItemID { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string UOMCode { get; set; }
        public Nullable<short> SaleContractMachineMasterID { get; set; }
        public Nullable<int> SaleContractFixItemID { get; set; }
        public Nullable<decimal> FixedRate { get; set; }
        public Nullable<byte> SequenceNumber { get; set; }
    
        public virtual SaleContractMaster SaleContractMaster { get; set; }
    }
}
