//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleContractEmployeeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleContractEmployeeMaster()
        {
            this.SaleContractEmployeeHistories = new HashSet<SaleContractEmployeeHistory>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<System.DateTime> FirstJoiningDate { get; set; }
        public Nullable<System.DateTime> LastLeftDate { get; set; }
        public Nullable<bool> IsLeft { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public string GenderCode { get; set; }
        public string MarritalStaus { get; set; }
        public string SSNNumber { get; set; }
        public string SINNumber { get; set; }
        public string DrivingLicenceNumber { get; set; }
        public Nullable<System.DateTime> DrivingLicenceExpireDate { get; set; }
        public string OtherEmailID { get; set; }
        public string PanNumber { get; set; }
        public string ESINumber { get; set; }
        public string ProvidentFundNumber { get; set; }
        public Nullable<System.DateTime> ProvidentFundApplicableDate { get; set; }
        public string BankACNumber { get; set; }
        public string BankIFSICode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Pincode { get; set; }
        public string EmergencyContactNumber1 { get; set; }
        public string EmergencyContactNumber2 { get; set; }
        public string MobileNumber { get; set; }
        public string UANNumber { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> CustomerMasterID { get; set; }
        public Nullable<int> CustomerBranchMasterID { get; set; }
        public string MiddleFullName { get; set; }
        public string ReasonOfLeaving { get; set; }
        public Nullable<short> CurrentESICZoneID { get; set; }
        public string BankName { get; set; }
        public string EmployeeImage { get; set; }
        public Nullable<bool> IsPoliceVerificationComplete { get; set; }
        public Nullable<bool> IsESICCardIssued { get; set; }
        public string BloodGroup { get; set; }
        public string CentreCode { get; set; }
        public Nullable<byte> BankMasterID { get; set; }
        public string ReasonForLeft { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleContractEmployeeHistory> SaleContractEmployeeHistories { get; set; }
    }
}
