//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderDeliveryDetail
    {
        public int ID { get; set; }
        public Nullable<int> SalesOrderDeliveryMasterID { get; set; }
        public Nullable<int> GeneralItemCodeID { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public string BarCode { get; set; }
        public string UomCode { get; set; }
        public string SalesUomCode { get; set; }
        public Nullable<double> BaseUOMQuantity { get; set; }
        public string BaseUOMCode { get; set; }
        public Nullable<double> DispatchedQuantity { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<int> GenTaxGroupMasterID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual SalesOrderDeliveryMaster SalesOrderDeliveryMaster { get; set; }
    }
}
