//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleContractOvertime
    {
        public long ID { get; set; }
        public Nullable<long> SaleContractMasterID { get; set; }
        public Nullable<decimal> FixedAmountForInvoice { get; set; }
        public Nullable<decimal> FixedAmountForSalaryCompliance { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> SaleContractManPowerItemID { get; set; }
        public Nullable<bool> IsOverTimeDaysFix { get; set; }
        public Nullable<byte> OTFixedDays { get; set; }
        public Nullable<bool> IsOTDaysOnTotalOff { get; set; }
        public Nullable<bool> IsOverTimeBillingDaysFix { get; set; }
        public Nullable<byte> OTBillingFixedDays { get; set; }
        public Nullable<bool> IsOTBillingDaysOnTotalOff { get; set; }
        public Nullable<byte> OverTimeDisplayFormat { get; set; }
    }
}
