//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesEnquiryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesEnquiryMaster()
        {
            this.SaleEnquiryDetails = new HashSet<SaleEnquiryDetail>();
            this.SalesQuotationMasters = new HashSet<SalesQuotationMaster>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerMasterID { get; set; }
        public Nullable<int> CustomerBranchMasterID { get; set; }
        public Nullable<short> ContactPersonID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<byte> StatusMode { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> ReferenceBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string EnquiryNumber { get; set; }
    
        public virtual CustomerMaster CustomerMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleEnquiryDetail> SaleEnquiryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesQuotationMaster> SalesQuotationMasters { get; set; }
    }
}
