//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoicePendingNotiAccEffect
    {
        public long ID { get; set; }
        public int SalesInvoiceMasterID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public byte CreationType { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string AccountXML { get; set; }
        public short AccBalsheetID { get; set; }
        public string TransactionType { get; set; }
        public string MenuCode { get; set; }
        public string NarrationRemark { get; set; }
        public long EffectiveLogID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<long> TransactionMainID { get; set; }
    
        public virtual SalesInvoiceMaster SalesInvoiceMaster { get; set; }
    }
}
