//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleContractSalaryTransactionDetail
    {
        public long ID { get; set; }
        public Nullable<long> SaleContractSalaryTransactionID { get; set; }
        public Nullable<int> SaleContractManPowerAllowanceID { get; set; }
        public Nullable<int> SaleContractManPowerDeductionID { get; set; }
        public Nullable<bool> IsAllowance { get; set; }
        public Nullable<byte> TransactionOrder { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AdjustedAmount { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
