//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderDeliveryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrderDeliveryMaster()
        {
            this.SalesOrderDeliveryDetails = new HashSet<SalesOrderDeliveryDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SalesOrderMasterID { get; set; }
        public string DeliveryNumber { get; set; }
        public Nullable<System.DateTime> DeliveryTransDate { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<int> ShipToCityID { get; set; }
        public Nullable<short> ShipToStateID { get; set; }
        public string ShipToAddress { get; set; }
        public string VehicalNumber { get; set; }
        public Nullable<short> GeneralShipperID { get; set; }
        public Nullable<decimal> FrieghtCharges { get; set; }
        public Nullable<bool> IsInvoiced { get; set; }
        public Nullable<long> SaleMasterID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CustomerBranchMasterID { get; set; }
        public Nullable<int> ContactPersonID { get; set; }
        public Nullable<int> GeneralUnitsID { get; set; }
        public Nullable<int> CustomerMasterID { get; set; }
        public string TransportationMode { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public Nullable<decimal> PurchaseAmount { get; set; }
        public Nullable<decimal> PurchaseBillAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDeliveryDetail> SalesOrderDeliveryDetails { get; set; }
        public virtual SalesOrderMaster SalesOrderMaster { get; set; }
    }
}
