//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleContractManPowerAssign
    {
        public long ID { get; set; }
        public Nullable<int> CustomerMasterID { get; set; }
        public Nullable<int> CustomerBranchMasterID { get; set; }
        public Nullable<long> SaleContractRequirementDetailsID { get; set; }
        public Nullable<long> SaleContractEmployeeMasterID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> UptoDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SaleContractManPowerItemID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> GeneralSiftMasterID { get; set; }
        public Nullable<bool> IsSalaryDaysCountFix { get; set; }
        public Nullable<byte> FixedDays { get; set; }
        public Nullable<decimal> OvertimePerHoursRate { get; set; }
        public Nullable<long> SaleContractMasterID { get; set; }
        public Nullable<decimal> AdditionalAmount { get; set; }
        public Nullable<bool> IsSalaryDaysOnWeeklyOff { get; set; }
        public Nullable<byte> ManPowerItemWeeklyOff { get; set; }
        public Nullable<bool> IsBillingDaysFixed { get; set; }
        public Nullable<byte> FixedBillingDays { get; set; }
        public Nullable<bool> IsBillingDaysOnWeeklyOff { get; set; }
    }
}
