//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleContractMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleContractMaster()
        {
            this.SaleContractRequirementDetails = new HashSet<SaleContractRequirementDetail>();
            this.SaleContractTermDetails = new HashSet<SaleContractTermDetail>();
        }
    
        public long ID { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<int> CustomerMasterID { get; set; }
        public Nullable<int> CustomerBranchMasterID { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<byte> SaleContractType { get; set; }
        public Nullable<bool> IsContractActive { get; set; }
        public Nullable<bool> IsRequirementPending { get; set; }
        public Nullable<byte> ContractBasicType { get; set; }
        public Nullable<long> OldSaleContractID { get; set; }
        public Nullable<byte> ContractRenewalStatus { get; set; }
        public Nullable<System.DateTime> NextBillingDate { get; set; }
        public Nullable<decimal> MaterialMaxAmount { get; set; }
        public Nullable<double> AgencyChargesInPercentage { get; set; }
        public Nullable<int> ContactPersonID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string CentreCode { get; set; }
        public Nullable<byte> BillingType { get; set; }
        public Nullable<decimal> BillingFixedAmount { get; set; }
        public Nullable<byte> FixedBillingType { get; set; }
        public Nullable<byte> ShortExtraPostingRateAccTo { get; set; }
        public Nullable<bool> IsConfidential { get; set; }
        public Nullable<bool> IsIncludeAllPostingForShortExtraRate { get; set; }
        public string Narration { get; set; }
        public Nullable<int> EmployeeMasterID { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public Nullable<System.DateTime> PurchaseOrderDate { get; set; }
        public Nullable<bool> IsDisplayPurchaseDetails { get; set; }
        public Nullable<byte> ApprovalStatus { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<short> ESICZoneMasterID { get; set; }
        public Nullable<short> PFZoneMasterID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleContractRequirementDetail> SaleContractRequirementDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleContractTermDetail> SaleContractTermDetails { get; set; }
    }
}
