//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoiceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesInvoiceMaster()
        {
            this.SalesInvoiceDetails = new HashSet<SalesInvoiceDetail>();
            this.SalesInvoicePendingNotiAccEffects = new HashSet<SalesInvoicePendingNotiAccEffect>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string CustomerInvoiceNumber { get; set; }
        public Nullable<int> CustomerMasterID { get; set; }
        public Nullable<int> SalesOrderMasterID { get; set; }
        public Nullable<decimal> TotalIInvoiceAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<int> StorageLocationID { get; set; }
        public Nullable<decimal> RoundUpAmount { get; set; }
        public Nullable<short> BalanceSheetID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CustomerBranchMasterID { get; set; }
        public Nullable<int> ContactPersonID { get; set; }
        public Nullable<int> GeneralUnitsID { get; set; }
        public Nullable<byte> InvoiceStatusFlag { get; set; }
        public Nullable<decimal> InvoicePaidAmount { get; set; }
        public Nullable<byte> Invoicetype { get; set; }
        public string TaxExemptionRemark { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string PurchaseOrderDate { get; set; }
        public string InvoiceDeductionName { get; set; }
        public Nullable<decimal> InvoiceDeductionAmount { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public Nullable<System.DateTime> BillingSpanEndDate { get; set; }
        public Nullable<byte> ApprovalStatus { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<byte> CancelApprovalStatus { get; set; }
        public Nullable<int> CancelApprovedBy { get; set; }
        public Nullable<System.DateTime> CancelApprovedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoiceDetail> SalesInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoicePendingNotiAccEffect> SalesInvoicePendingNotiAccEffects { get; set; }
        public virtual SalesOrderMaster SalesOrderMaster { get; set; }
    }
}
