//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrderMaster()
        {
            this.SalesInvoiceMasters = new HashSet<SalesInvoiceMaster>();
            this.SalesOrderDeliveryMasters = new HashSet<SalesOrderDeliveryMaster>();
            this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
            this.TempSalesInvoiceMasters = new HashSet<TempSalesInvoiceMaster>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SalesQuotationMasterID { get; set; }
        public string SalesOrderNumber { get; set; }
        public Nullable<System.DateTime> SalesOrderDate { get; set; }
        public Nullable<int> CustomerMasterID { get; set; }
        public string PurchaseOrderNumberClient { get; set; }
        public Nullable<decimal> TotalTaxAmount { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> ShippingHandling { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TradeIn { get; set; }
        public Nullable<double> TotalPOAmount { get; set; }
        public Nullable<double> RoundOffAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> GeneralUnitsID { get; set; }
        public Nullable<int> CustomerBranchMasterID { get; set; }
        public Nullable<int> ContactPersonID { get; set; }
        public Nullable<byte> SOStatus { get; set; }
        public Nullable<bool> IsRequirmentCreated { get; set; }
        public Nullable<byte> ApprovalStatus { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        public virtual CustomerMaster CustomerMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoiceMaster> SalesInvoiceMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDeliveryMaster> SalesOrderDeliveryMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
        public virtual SalesQuotationMaster SalesQuotationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempSalesInvoiceMaster> TempSalesInvoiceMasters { get; set; }
    }
}
