//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleContractManPowerAllowance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleContractManPowerAllowance()
        {
            this.SaleContractManPowerAllowanceSumOfs = new HashSet<SaleContractManPowerAllowanceSumOf>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SaleContractManPowerItemID { get; set; }
        public Nullable<byte> SalaryAllowanceMasterID { get; set; }
        public Nullable<decimal> FixedAmount { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<byte> CalculateOn { get; set; }
        public Nullable<short> MapAccountID { get; set; }
        public Nullable<bool> IsGenderSpecific { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public Nullable<decimal> RangeFrom { get; set; }
        public Nullable<decimal> RangeUpto { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<byte> SalaryAllowanceRulesID { get; set; }
        public Nullable<decimal> CalculatedAmount { get; set; }
        public Nullable<decimal> CalculateOnFixedAmount { get; set; }
    
        public virtual SaleContractManPowerItem SaleContractManPowerItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleContractManPowerAllowanceSumOf> SaleContractManPowerAllowanceSumOfs { get; set; }
    }
}
