//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesQuotationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesQuotationMaster()
        {
            this.SaleQuotationDetails = new HashSet<SaleQuotationDetail>();
            this.SalesOrderMasters = new HashSet<SalesOrderMaster>();
        }
    
        public int ID { get; set; }
        public string QuotationNumber { get; set; }
        public Nullable<int> CustomerMasterID { get; set; }
        public Nullable<short> CreditPeriod { get; set; }
        public string CreditPeriodUnit { get; set; }
        public string TitleTo { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> SalesEnquiryMasterID { get; set; }
        public Nullable<double> TotalBillAmount { get; set; }
        public Nullable<double> RoundOffAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ContactPersonID { get; set; }
        public Nullable<int> CustomerBranchMasterID { get; set; }
        public Nullable<int> GeneralUnitsID { get; set; }
    
        public virtual CustomerMaster CustomerMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleQuotationDetail> SaleQuotationDetails { get; set; }
        public virtual SalesEnquiryMaster SalesEnquiryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderMaster> SalesOrderMasters { get; set; }
    }
}
