//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleContractAttendance
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public Nullable<int> CustomerMasterID { get; set; }
        public Nullable<int> CustomerBranchMasterID { get; set; }
        public Nullable<int> SaleContractManPowerItemID { get; set; }
        public Nullable<byte> AttendanceStatus { get; set; }
        public Nullable<bool> IsHalfDayLeave { get; set; }
        public Nullable<double> OvertimeHours { get; set; }
        public Nullable<long> SaleContractEmployeeMasterID { get; set; }
        public Nullable<long> SaleContractMasterID { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> SalaryGenerateID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string AttendanceForMonth { get; set; }
        public Nullable<double> TotalAttendance { get; set; }
        public Nullable<byte> TotalDays { get; set; }
        public Nullable<long> SaleContractBillingSpanID { get; set; }
        public Nullable<byte> TotalBillingDays { get; set; }
        public Nullable<byte> TotalWeeklyOffDays { get; set; }
        public Nullable<byte> TotalMonthlyBillingOffDays { get; set; }
        public Nullable<byte> TotalOverTimeSalaryDays { get; set; }
        public Nullable<byte> TotalOverTimeBillingDays { get; set; }
        public Nullable<byte> TotalWeeklyOffBillingDays { get; set; }
        public Nullable<long> SaleContractManPowerAssignID { get; set; }
        public Nullable<long> SalaryForManPowerItemID { get; set; }
        public Nullable<byte> ApprovalStatus { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    }
}
