//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleContractManPowerItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleContractManPowerItem()
        {
            this.SaleContractManPowerAllowances = new HashSet<SaleContractManPowerAllowance>();
            this.SaleContractManPowerDeductions = new HashSet<SaleContractManPowerDeduction>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public Nullable<short> DesignationMasterID { get; set; }
        public Nullable<decimal> BasicSalayAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> CustomerBranchMasterID { get; set; }
        public Nullable<int> CustomerMasterID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> FixedSalaryAmount { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> NetSalaryAmount { get; set; }
        public Nullable<bool> IsRevised { get; set; }
        public Nullable<int> ParentManPowerItemID { get; set; }
        public string BillingDisplayName { get; set; }
        public Nullable<System.DateTime> WithEffectiveFromDate { get; set; }
        public Nullable<System.DateTime> WithEffectiveUptoDate { get; set; }
        public Nullable<byte> ApprovalStatus { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleContractManPowerAllowance> SaleContractManPowerAllowances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleContractManPowerDeduction> SaleContractManPowerDeductions { get; set; }
    }
}
