//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskNotificationDetail
    {
        public int ID { get; set; }
        public int TaskNotificationMasterID { get; set; }
        public int GeneralTaskReportingDetailsID { get; set; }
        public Nullable<int> NextGeneralTaskReportingDetailsID { get; set; }
        public Nullable<bool> IsLastRecordFlag { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string MenuCodeLink { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsParallalyUpdated { get; set; }
        public string ApplicationDate { get; set; }
        public Nullable<bool> IsEngaged { get; set; }
        public Nullable<int> EnagedByUserID { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual GeneralTaskReportingDetail GeneralTaskReportingDetail { get; set; }
        public virtual TaskNotificationMaster TaskNotificationMaster { get; set; }
    }
}
