//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskNotificationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskNotificationMaster()
        {
            this.TaskNotificationDetails = new HashSet<TaskNotificationDetail>();
        }
    
        public int ID { get; set; }
        public string TaskCode { get; set; }
        public Nullable<int> GeneralTaskReportingMasterID { get; set; }
        public string EntitytableName { get; set; }
        public string EntityPKName { get; set; }
        public Nullable<int> EntityPKValue { get; set; }
        public int PersonID { get; set; }
        public string PersonType { get; set; }
        public string Status { get; set; }
        public Nullable<int> LastApprovalStatus { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual GeneralTaskReportingMaster GeneralTaskReportingMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskNotificationDetail> TaskNotificationDetails { get; set; }
    }
}
