//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempSaleContractSalaryTransaction
    {
        public long ID { get; set; }
        public Nullable<long> SaleContractBillingSpanID { get; set; }
        public Nullable<long> SaleContractEmployeeMasterID { get; set; }
        public Nullable<int> SaleContractManPowerItemID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> TotalDeduction { get; set; }
        public Nullable<decimal> NetPayable { get; set; }
        public Nullable<decimal> EmployerContributionTotal { get; set; }
        public Nullable<decimal> TotalSalary { get; set; }
        public Nullable<bool> IsRemoveForAdjustment { get; set; }
        public Nullable<double> TotalDays { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsSalaryCompliance { get; set; }
        public Nullable<decimal> AdjustedTotalSalary { get; set; }
        public Nullable<double> AdjustedTotalDays { get; set; }
        public Nullable<System.DateTime> SalaryComplianceDate { get; set; }
        public Nullable<decimal> BasicAmount { get; set; }
        public Nullable<bool> IsSalaryPaid { get; set; }
        public Nullable<decimal> AdjustedBasicAmount { get; set; }
        public Nullable<short> ESICZoneID { get; set; }
        public Nullable<decimal> TotalEarning { get; set; }
        public Nullable<bool> IsArrears { get; set; }
        public Nullable<decimal> AdjustedNetPayable { get; set; }
    }
}
