//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public long ID { get; set; }
        public int UserID { get; set; }
        public string IP { get; set; }
        public string MachinName { get; set; }
        public Nullable<int> UserLogsId { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
