//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARIndia.DataAccessLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorFinanceDetail
    {
        public int ID { get; set; }
        public int VendorID { get; set; }
        public string CreditLimit { get; set; }
        public string Incoterms { get; set; }
        public string AccountNo { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string BankAddress { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<double> CashDiscount { get; set; }
        public Nullable<double> RebatePercent { get; set; }
        public Nullable<bool> CashOnDelivery { get; set; }
        public Nullable<bool> CurrentDatedCheque { get; set; }
        public Nullable<bool> Credit { get; set; }
    
        public virtual GeneralSupplierMaster GeneralSupplierMaster { get; set; }
    }
}
